// Login Page
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_ERROR_MSG = 'LOGIN_ERROR_MSG';
export const LOGIN_SUCCESS_MSG = 'LOGIN_SUCCESS_MSG';

//Message Reducer
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const CONFIRM = 'CONFIRM';

//Product

export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_FAILED = 'GET_PRODUCT_LIST_FAILED';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'GET_PRODUCT_DETAIL_FAILED';
export const UPDATE_PRODUCT_DETAIL = 'UPDATE_PRODUCT_DETAIL';

export const SHOW_PRODUCT_DETAIL_MODAL = 'SHOW_PRODUCT_DETAIL_MODAL';
export const HIDE_PRODUCT_DETAIL_MODAL = 'HIDE_PRODUCT_DETAIL_MODAL';